#!/bin/bash

#############################################################
# GEFS RUNALL 
# 09/01/2023 Jun Du, create for run all scripts 
# 2nd part to process 222-384hr
#############################################################

########################################
# Preliminary data setup step
########################################

set -xa
export PS4='$SECONDS + ' 
date

unset MPICH_RANK_REORDER_DISPLAY

###########################################################
# obtain unique process id (pid) and make temp directories
###########################################################
export DATA=${DATA:-${DATAROOT:?}/${jobid:?}}
mkdir -p $DATA
rm -rf $DATA/*
cd $DATA

msg="JOB $job HAS BEGUN"
postmsg "$msg"

#
# Run setpdy and initialize PDY variables
#

export cycle=${cycle:-t${cyc}z}
setpdy.sh
. ./PDY

##################################################
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
##################################################

export SENDCOM=${SENDCOM:-YES}
export SENDECF=${SENDECF:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDDBN_NTC=${SENDDBN_NTC:-NO}

export HOMEgefs=${HOMEgefs:-$PACKAGEROOT/gefs.${gefs_ver}} 
export EXECgefs=${EXECgefs:-$HOMEgefs/exec}
export PARMgefs=${PARMgefs:-$HOMEgefs/parm}
export USHgefs=${USHgefs:-$HOMEgefs/ush}
export FIXgefs=${FIXgefs:-$HOMEgefs/fix}
export SCRIPTSgefs=${SCRIPTSgefs:-$HOMEgefs/scripts}

###################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-gefs}
export RUN=${RUN:-gefs}

export IOBUF_PARAMS='*:size=8M:count=8'

##############################################
# Define running directory and COM directories
##############################################

## PDY not included here as pull data from PDYm1 as well

export COMINgefs=${COMINgefs:-$GESROOT/${RUN}}

export COMOUT=${COMOUT:-$(compath.py -o $NET/${gefs_ver})/${RUN}.${PDY}}

if [ ! -d $COMOUT/ensprod ] ; then 
 mkdir -p $COMOUT/ensprod
 mkdir -p $COMOUT/wmo
fi

export pgmout="OUTPUT.$$"

#######################################################
# Pass information which is needed to run the Script
#######################################################

# export VERBOSE=YES

###################################################
# Execute the Script exrrfs_ensprod.sh.ecf

rm -rf poe.*

hrlist_link="006 012 018 024 030 036 042 048 054 060 066 072 078 084 090 096 102 108 114 120 126 132 138 144 150 156 162 168 174 180 186 192 198 204 210 216 222 228 234 240 246 252 258 264 270 276 282 288 294 300 306 312 318 324 330 336 342 348 354 360 366 372 378 384"
hrlist="222 228 234 240 246 252 258 264 270 276 282 288 294 300 306 312 318 324 330 336 342 348 354 360 366 372 378 384"

for hr in $hrlist_link
do
echo "$SCRIPTSgefs/exgefs_enspost_link.sh.ecf $hr $type" >> poe.link.all
done

for hr in $hrlist
do
echo "$SCRIPTSgefs/exgefs_enspost.sh.ecf $hr $type" >> poe.ensprod.all
done


chmod 775  poe.link.all
chmod 775 poe.ensprod.all

mpiexec  -n $NTASK_LINK -ppn $PTILE_LINK --cpu-bind verbose,core cfp ./poe.link.all
export err=$?; err_chk
mpiexec  -n $NTASK -ppn $PTILE --cpu-bind verbose,core cfp ./poe.ensprod.all
export err=$?; err_chk


msg="JOB $job HAS COMPLETED NORMALLY."
postmsg "$msg"
date


cd $DATAROOT
if [ $KEEPDATA = NO ]; then rm -rf $DATA; fi

date
