#!/bin/sh

#############################################################
#
# REPS PRE-PROCESS
# 07/10/2023 Jun Du, read in GEFS grib data for sref ensemble post 
# 04/08/2025 Jun Du, modified it to be reps.v1.0.0 for implementation
#
#############################################################

########################################
# Preliminary data setup step
########################################

set -xa
export PS4='$SECONDS + ' 
date

unset MPICH_RANK_REORDER_DISPLAY

###################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-reps}
export RUN=${RUN:-sref}

export IOBUF_PARAMS='*:size=8M:count=8'

###############################################################
# This block can be modified for different Production test
# environment. This is used for operational testings
###############################################################

export COMINgefs=${COMINgefs:-$(compath.py ${envir}/com/gefs/${gefs_ver}/gefs)}

export HOMEreps=${HOMEreps:-$NWROOT/reps.${reps_ver}} 
export EXECreps=${EXECreps:-$HOMEreps/exec}
export PARMreps=${PARMreps:-$HOMEreps/parm}
export USHreps=${USHreps:-$HOMEreps/ush}
export FIXreps=${FIXreps:-$HOMEreps/fix}
export SCRIPTSreps=${SCRIPTSreps:-$HOMEreps/scripts}
export ndate=/apps/ops/prod/nco/core/prod_util.v2.0.8/exec/ndate

###########################################################
# obtain unique process id (pid) and make temp directories
###########################################################

export pid=$$
export DATA=${DATA:-${DATAROOT}/reps_enspost_ensprodpreproc_${NEST}_${cyc}_${envir}.${pid}}
mkdir -p $DATA
rm -rf $DATA/*

export DATA2=${DATA2:-${DATAROOT}/reps_enspost_thin_${NEST}_${cyc}_${envir}.${pid}}
mkdir -p $DATA2
rm -rf $DATA2/*

cd $DATA

####################################
# Determine Job Output Name on System
####################################
export pgmout="OUTPUT.$$"

export cycle=${cycle:-t${cyc}z}

##################################################
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
##################################################

export SENDCOM=${SENDCOM:-YES}
export SENDECF=${SENDECF:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDDBN_NTC=${SENDDBN_NTC:-NO}

###################################
# Set up the UTILITIES
###################################

msg="JOB $job HAS BEGUN"
postmsg "$msg"

#
# Run setpdy and initialize PDY variables
#


export cycle=${cycle:-t${cyc}z}

setpdy.sh
. ./PDY

echo have PDY as $PDY

##############################################
# Define running directory and COM directories
##############################################

export COMOUT=${COMOUT:-$(compath.py -o $NET/${reps_ver})/${RUN}.${PDY}/$cyc}
export GESOUT=$COMOUT/pgrb

if [ ! -d $COMOUT ] ; then 
 mkdir -p $COMOUT/ensprod
fi
if [ ! -d $GESOUT ] ; then 
 mkdir -p $GESOUT
fi

#######################################################
# Pass information which is needed to run the Script
#######################################################

# export VERBOSE=YES

###################################################
# Execute the Script exreps_enspost_ensprod.sh

#hrlist="000 006 012 018 024 030 036 042 048 054 060 066 072 078 084 090 096 102 108 114 120 126 132 138 144 150 156 162 168 174 180 186 192 198 204 210 216 222 228 234 240 246 252 258 264 270 276 282 288 294 300 306 312 318 324 330 336 342 348 354 360 366 372 378 384"
 hrlist="000 006 012 018 024 030 036 042 048 054 060 066 072 078 084 090"

mems="01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31"

region=$NEST

for mem in $mems
do
if [ $mem = 01 ]; then name=c00; fi
if [ $mem = 02 ]; then name=p01; fi
if [ $mem = 03 ]; then name=p02; fi
if [ $mem = 04 ]; then name=p03; fi
if [ $mem = 05 ]; then name=p04; fi
if [ $mem = 06 ]; then name=p05; fi
if [ $mem = 07 ]; then name=p06; fi
if [ $mem = 08 ]; then name=p07; fi
if [ $mem = 09 ]; then name=p08; fi
if [ $mem = 10 ]; then name=p09; fi
if [ $mem = 11 ]; then name=p10; fi
if [ $mem = 12 ]; then name=p11; fi
if [ $mem = 13 ]; then name=p12; fi
if [ $mem = 14 ]; then name=p13; fi
if [ $mem = 15 ]; then name=p14; fi
if [ $mem = 16 ]; then name=p15; fi
if [ $mem = 17 ]; then name=p16; fi
if [ $mem = 18 ]; then name=p17; fi
if [ $mem = 19 ]; then name=p18; fi
if [ $mem = 20 ]; then name=p19; fi
if [ $mem = 21 ]; then name=p20; fi
if [ $mem = 22 ]; then name=p21; fi
if [ $mem = 23 ]; then name=p22; fi
if [ $mem = 24 ]; then name=p23; fi
if [ $mem = 25 ]; then name=p24; fi
if [ $mem = 26 ]; then name=p25; fi
if [ $mem = 27 ]; then name=p26; fi
if [ $mem = 28 ]; then name=p27; fi
if [ $mem = 29 ]; then name=p28; fi
if [ $mem = 30 ]; then name=p29; fi
if [ $mem = 31 ]; then name=p30; fi

 for hr in $hrlist
 do
  echo "$USHreps/enspost_preprocess.sh $PDY ${cyc} ${mem} ${name} $hr ${region}" >> poe.reps
  echo "$USHreps/enspost_thin.sh $PDY ${cyc} ${mem} ${name} $hr ${region}" >> poe.repsmem
 done


done  #mem
 
chmod 775 poe.reps  
# export NODES=6

# ./poe.fv3
#mpiexec -n $NTASK -ppn $PTILE --cpu-bind verbose,core cfp ./poe.reps
#mpiexec -n $NTASK -ppn $NTASK --cpu-bind verbose,core cfp ./poe.reps
mpiexec -n $NTASK -ppn 1 --cpu-bind verbose,core cfp ./poe.reps
export err=$?; err_chk

######################################
if [ $err -ne 0 ]
 then
  msg="FATAL ERROR: reps subdomain files are not produced properly"
  err_exit $msg
else
 chmod 775 poe.repsmem 
 mpiexec -n $NTASK -ppn 1 --cpu-bind verbose,core cfp ./poe.repsmem
 export err=$?; err_chk
fi
if [ $err -ne 0 ]
 then
  msg="FATAL ERROR: reps thin files are not produced properly"
  err_exit $msg
else
 names="c00 p01 p02 p03 p04 p05 p06 p07 p08 p09 p10 p11 p12 p13 p14 p15 p16 p17 p18 p19 p20 p21 p22 p23 p24 p25 p26 p27 p28 p29 p30"
 for name in $names
 do
# hours="000 006 012 018 024 030 036 042 048 054 060 066 072 078 084 090 096 102 108 114 120 126 132 138 144 150 156 162 168 174 180 186 192 198 204 210 216 222 228 234 240 246 252 258 264 270 276 282 288 294 300 306 312 318 324 330 336 342 348 354 360 366 372 378 384"
  hours="000 006 012 018 024 030 036 042 048 054 060 066 072 078 084 090"
  for hr in $hours
  do
   cat $DATA2/$RUN.t${cyc}z.$name.f$hr.grib2 >> $GESOUT/$RUN.t${cyc}z.$name.pgrb$region.grib2
  done 
  $WGRIB2 $GESOUT/$RUN.t${cyc}z.$name.pgrb$region.grib2  -s >  $GESOUT/$RUN.t${cyc}z.$name.pgrb$region.grib2.idx
 done
fi
######################################

#done  #mem

cd $DATAROOT
#if [ $KEEPDATA = NO ]; then rm -rf $DATA; fi

date
