#!/bin/ksh 

########################################
# Preliminary data setup step
#
# 05/01/2023, Jun Du: added a timelag version (type=timelag, single)
#
########################################
set -xa
export PS4='$SECONDS + ' 
date

########################################################### 
# obtain unique process id (pid) and make temp directories
###########################################################
export DATA=${DATA:-${DATAROOT:?}/${jobid:?}}
mkdir -p $DATA
rm -rf $DATA/*
cd $DATA

msg="JOB $job HAS BEGUN"
postmsg  "$msg"

export cycle=${cycle:-t${cyc}z}
setpdy.sh
. ./PDY

##################################################
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
##################################################
export SENDCOM=${SENDCOM:-YES}
export SENDECF=${SENDECF:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDDBN_NTC=${SENDDBN_NTC:-NO}

###############################################################
# This block can be modified for different Production test
# environment. This is used for operational testings
###############################################################

## PDY not included here as pull data from PDYm1 as well

# Save it for time lag ensemble
export COMINhiresw=${COMINhiresw:-$(compath.py ${envir}/com/hiresw/${hiresw_ver}/hiresw)}
export COMINnam=${COMINnam:-$GESROOT/rrfs}
export COMINhrrr=${COMINhrrr:-$GESROOT/rrfs}

export HOMErrfs=${HOMErrfs:-$PACKAGEROOT/rrfs.${rrfs_ver}}
export EXECrrfs=${EXECrrfs:-$HOMErrfs/exec}
export PARMrrfs=${PARMrrfs:-$HOMErrfs/parm}
export USHrrfs=${USHrrfs:-$HOMErrfs/ush}
export FIXrrfs=${FIXrrfs:-$HOMErrfs/fix}
export SCRIPTSrrfs=${SCRIPTSrrfs:-$HOMErrfs/scripts}

###################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-rrfs}
export RUN=${RUN:-rrfs}

export IOBUF_PARAMS='*:size=8M:count=8'
##############################################
# Define running directory and COM directories
##############################################

export COMOUT=${COMOUT:-$(compath.py -o $NET/${rrfs_ver})/$RUN.${PDY}/$type}

if [ ! -d $COMOUT ] ; then
 mkdir -p $COMOUT/ensprod
 mkdir -p $COMOUT/verf_g2g
fi

export pgmout="OUTPUT.$$"
 
########################################################
# Execute the script.

$HOMErrfs/scripts/exrrfs_enspost_eas_1.sh.ecf $type
########################################################

msg="JOB $job HAS COMPLETED NORMALLY."
postmsg "$msg"

cd $DATAROOT
if [ $KEEPDATA = NO ]; then rm -rf $DATA; fi

date
