Check HREFv3 conus for 2019091600 at Mon Sep 16 16:02:19 UTC 2019
 
-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-
 Check existence of 48 h HREF output files
--------------------------------
-rw-r--r-- 1 Matthew.Pyle g01 5570677 Sep 16 09:28 href.t00z.conus.avrg.f48.grib2
-rw-r--r-- 1 Matthew.Pyle g01 4293785 Sep 16 09:30 href.t00z.conus.eas.f48.grib2
-rw-r--r-- 1 Matthew.Pyle g01 2384905 Sep 16 09:28 href.t00z.conus.ffri.f48.grib2
-rw-r--r-- 1 Matthew.Pyle g01 1433572 Sep 16 09:28 href.t00z.conus.lpmm.f48.grib2
-rw-r--r-- 1 Matthew.Pyle g01 35551312 Sep 16 09:28 href.t00z.conus.mean.f48.grib2
-rw-r--r-- 1 Matthew.Pyle g01 4467166 Sep 16 09:28 href.t00z.conus.pmmn.f48.grib2
-rw-r--r-- 1 Matthew.Pyle g01 38715175 Sep 16 09:28 href.t00z.conus.prob.f48.grib2
-rw-r--r-- 1 Matthew.Pyle g01 37621344 Sep 16 09:28 href.t00z.conus.sprd.f48.grib2
 
-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-
 Check for job errors
--------------------------------
/gpfs/hps2/ptmp/Matthew.Pyle/logfiles_href
 
Details of last completed cycle: 
 
       CYCLE                    TASK                       JOBID               STATE         EXIT STATUS     TRIES      DURATION
================================================================================================================================
201909160000            preproc_hrrr                       19156           SUCCEEDED                   0         1         250.0
201909160000             preproc_nam                       19596           SUCCEEDED                   0         1         246.0
201909160000             preproc_fv3                       24116           SUCCEEDED                   0         1          18.0
201909160000           eas_climo_bin                       24226           SUCCEEDED                   0         1          32.0
201909160000               eas_calib                       24262           SUCCEEDED                   0         1          44.0
201909160000                 eas_gen                       24296           SUCCEEDED                   0         1         617.0
201909160000                 ffg_gen                       24227           SUCCEEDED                   0         1          19.0
201909160000                 ensprod                       24263           SUCCEEDED                   0         1        1414.0
201909160000              href_awips                       24485           SUCCEEDED                   0         1         100.0
201909160000             href_gempak                       24484           SUCCEEDED                   0         1        1970.0
